# Generated by Django 4.2.16 on 2024-12-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(blank=True, max_length=64, null=True)),
                ('numeroUsuario', models.CharField(blank=True, max_length=32, null=True)),
                ('direccionUsuario', models.CharField(blank=True, max_length=64, null=True)),
                ('areaUsuario', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
