# Generated by Django 5.1.3 on 2024-12-20 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app3", "0004_rename_contra_datosusuario_contrasena"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datosusuario",
            name="apellido",
        ),
        migrations.RemoveField(
            model_name="datosusuario",
            name="contrasena",
        ),
        migrations.RemoveField(
            model_name="datosusuario",
            name="email",
        ),
        migrations.RemoveField(
            model_name="datosusuario",
            name="nombre",
        ),
        migrations.RemoveField(
            model_name="datosusuario",
            name="username",
        ),
    ]
