# Generated by Django 5.1.4 on 2024-12-21 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app3", "0005_remove_datosusuario_apellido_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datosusuario",
            old_name="profesion",
            new_name="profesionUsuario",
        ),
    ]
