# Generated by Django 5.1.4 on 2024-12-21 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app3", "0006_rename_profesion_datosusuario_profesionusuario"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datosusuario",
            old_name="profesionUsuario",
            new_name="profesion",
        ),
    ]
